apiVersion: apps/v1
kind: Deployment
metadata:
  name: pruebacicd
spec:
  replicas: 1
  selector:
    matchLabels: ~
  strategy:
    app: pruebacicd
    type:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
        minReadySeconds: 5
    app: pruebacicd
  template:
    metadata:
      labels:
        app: pruebacicd
        role: pruebacicd
    spec:
      containers:
        - name: pruebacicd
          image: itzelmunguia/pruebacicd:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: pruebacicd

---
apiVersion: v1
kind: Service
metadata:
  name: pruebacicd
  labels:
    app: pruebacicd
spec:
  selector:
   app: pruebacicd
  type: LoadBalancer
  ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 80
  selector:
    role: pruebacicd
