apiVersion: apps/v1
kind: Deployment
metadata:
  name: pruebaCICD
spec:
  selector:
   matchLabels:
    app: pruebaCICD
  replicas: 1
  template:
    metadata:
      labels:
        app: pruebaCICD
        role: pruebaCICD
    spec:
      containers:
        - name: pruebaCICD
          image: itzelmun/pruebaCICD:latest 
            #imagePullPolicy: Never
          ports:
            - containerPort: 80
              name: pruebaCICD

---
apiVersion: v1
kind: Service
metadata:
  name: pruebaCICD
  labels:
    app: pruebaCICD
spec:
  selector:
   app: pruebaCICD
  type: LoadBalancer
  ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 80
  selector:
    role: pruebaCICD

