apiVersion: apps/v1
kind: Deployment
metadata:
  name: prueba-gha2
spec:
  selector:
   matchLabels:
    app: prueba-gha2
  replicas: 1
  template:
    metadata:
      labels:
        app: prueba-gha2
        role: prueba-gha2
    spec:
      containers:
        - name: prueba-gha2
          image: itzelmun/pruebaCICD:latest 
            #imagePullPolicy: Never
          ports:
            - containerPort: 80
              name: prueba-gha2

---
apiVersion: v1
kind: Service
metadata:
  name: prueba-gha2
  labels:
    app: prueba-gha2
spec:
  selector:
   app: prueba-gha2
  type: LoadBalancer
  ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 80
  selector:
    role: prueba-gha2

